### ISSUE TITLE
Potential new logo, and an svg version

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1]
We have permanently settled with PolyMC as the name because I already registered the polymc.org domains. We have also temporarily settled with Ouroboros as our logo.

We have a working logo (thank you to @ZekeSmith), but if anyone has any objections/suggested changes please feel free to voice them.

![polymc_BASED_EDITION](https://user-images.githubusercontent.com/65276418/149596513-bdb4dc6f-b038-49ec-9422-d5643dac48af.png)

**Comment by ghost** [comment]
The name PolyMC is already used by https://github.com/TheEpicBlock/PolyMc

**Comment by ghost** [comment]
> The name PolyMC is already used by https://github.com/TheEpicBlock/PolyMc

I've asked that project's maintainer if it's alright for us to use the name (probably is because it's LGPL). If he says yes we'll keep it unless someone suggests a better name

**Comment by ghost** [comment]
@LiamMCW The maintainer of that project said it's alright for us to use it. Thank you for letting me know though!

**Comment by TheFrenchGhosty** [comment]
@binex-dsk Some random ideas:

ManyMC
UnitedMC
MuchMC (you can even use doge as a mascot with this one :eyes: )

PS: thanks for this fork, I'm really looking forward to have a MultiMC that isn't ruined by the developer's ego, (I'm waiting for a .deb/a debian repo and an AUR package - I'm currently on GDLauncher... but it's not great).

**Comment by ghost** [comment]
Thanks for the ideas and you're welcome! I've got no clue how to make a debian repo, let alone a .deb, but later during break (probably after Christmas) I'll work on that, along with a Gentoo ebuild. @LennyMcLennington can make the AUR package, and it and the ebuild should be easy because we've already got our own MultiMC packages, so we just need to change the repo.

**Comment by TheFrenchGhosty** [comment]
@binex-dsk I mean it's not ideal... but what about an AppImage?

**Comment by ghost** [comment]
> @binex-dsk I mean it's not ideal... but what about an AppImage?

Not sure how to make those either. I can work on that later as well.

**Comment by ghost** [comment]
We're gonna stick with PolyMC because I've already done a lot of work using this name, like buying a domain (polymc.org).

We now just need to settle on the final logo

**Comment by ghost** [comment]
yemou on Discord whipped up a quick logo for us. It doesn't use Ouroboros as a base but if anyone would like to do that it would be greatly appreciated.

![yemou](https://user-images.githubusercontent.com/65276418/147580755-9a2ad5f3-c0ed-4437-a14d-279af5f41fe3.png)

**Comment by ghost** [comment]
new version by lovetocode999 

![image](https://user-images.githubusercontent.com/65276418/147800565-315bd3f9-0c00-4b25-9e95-080d4c99b5a8.png)

He also is working on vectorizing Ouroboros and making a version based off of that so we'll probably end up using that as our final logo. This will be the temporary logo for now

**Comment by ghost** [comment]
cool ouroboros vector by lenny
![ouroboros2](https://user-images.githubusercontent.com/65276418/147837295-f803dbbc-2935-494c-ae8a-625ddb2c9397.png)

will use this for now, if anyone wants to make a cool version with a minecraft background or something that would be nice

**Comment by d-513** [comment]
IMO a flat, minecrafty logo would fit the launcher well. Flat ouroboros with maybe some Minecraft block as background would fit well

**Comment by yemouu** [comment]
The yellow circle makes me a think a gold block might look good there

**Comment by ghost** [comment]
That's a good idea. Gold block SVG laid behind the Ouroboros would be very nice if anyone's willing.

**Comment by karolinaabb** [comment]
Hi, I've made this pixel logo from scratch. I'm open to feedback! Let me know if there's anything worth tweaking.
![Sprite-0002-scaled](https://user-images.githubusercontent.com/97206652/148320498-206389cd-6e8c-46a4-8795-2dd864099c34.png)

**Comment by d-513** [comment]
> @karolinabb Hi, I've made this pixel logo from scratch. I'm open to feedback! Let me know if there's anything worth tweaking.
> ![Sprite-0002-scaled](https://user-images.githubusercontent.com/97206652/148320498-206389cd-6e8c-46a4-8795-2dd864099c34.png)

Love it. Can you upload SVG version?

**Comment by karolinaabb** [comment]
The original is made in LibreSprite (raster) which then I converted to svg by [Pixels to svg](https://codepen.io/shshaw/pen/XbxvNj) 
Here are the files: https://github.com/karolinaabb/PolyMC-logo

**Comment by d-513** [comment]
> The original is made in LibreSprite (raster) which then I converted to svg by [Pixels to svg](https://codepen.io/shshaw/pen/XbxvNj) Here are the files: https://github.com/karolinaabb/PolyMC-logo

I would think such a converter would lose quality, but it looks like the svg is properly made and small size (3KB), so good job.

**Comment by ghost** [comment]
> Hi, I've made this pixel logo from scratch. I'm open to feedback! Let me know if there's anything worth tweaking. ![Sprite-0002-scaled](https://user-images.githubusercontent.com/97206652/148320498-206389cd-6e8c-46a4-8795-2dd864099c34.png)

I like this and the verdict seems to be that this fits Minecraft very well. We will set that as our temporary logo and I'll commit this icon.

**Comment by ZekeZDev** [comment]
I really like the idea behind this project and I was wondering if you wanted any help on the logo design process. I have a couple of ideas and would love to help with development. I currently mainly work as a hobbyist but I have done some work on some other opensource project logos for example the current [bottles logo](https://github.com/bottlesdevs/Bottles). I have some time tomorrow and I would love to help. 

If your also interested in help with your website I am willing to contribute to that, I mainly have experience in jamstack which I believe would suit well for a project website.

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148562545-e47477a4-cd10-43eb-9a47-44595f3b4096.png)
Here's a quick concept I made. Obviously not final but this is the sort of design I am leaning to that I think would stand out but be familiar.

**Comment by ZekeZDev** [comment]
> > Hi, I've made this pixel logo from scratch. I'm open to feedback! Let me know if there's anything worth tweaking. ![Sprite-0002-scaled](https://user-images.githubusercontent.com/97206652/148320498-206389cd-6e8c-46a4-8795-2dd864099c34.png)
> 
> I like this and the verdict seems to be that this fits Minecraft very well. We will set that as our temporary logo and I'll commit this icon.

I agree that this logo is very good, but I dont think it fits minecraft having the pixel art and gold it seems more like some sort of indie rpg then a minecraft launcher. Designs like the minecraft launcher and multimc launcher work well because it is clear what it is launching. gold pixel art with a snake on it isnt clear of anything. 

This doesnt include launchers like curseforge and technic, neither of their logos resemble minecraft however they have a familar connection with the application someone searching curseforge is going to understand the curseforge launcher is for minecraft mods and the logo is already familiar.

If I wasnt actively looking through the description of this app on flatpak I would have had no idea it was for minecraft with most of the proposed logos. (Except yemou)

**Comment by d-513** [comment]
@ZekeSmith Looking at it from this perspective I understand your points. At least in my opinion, it would be nice to have the logo in the general art style for Linux icons

**Comment by ZekeZDev** [comment]
![Polymchd](https://user-images.githubusercontent.com/81902668/148633786-3a9f841b-b596-40d3-815d-c4102d81466e.png)
What do you guys think of this?

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148633833-71f8202d-d96a-492c-897a-2b7e3353433d.png)
Here's what it looks like as a desktop icon

**Comment by edward-shen** [comment]
If I can comment and vote as a random, I definitely like @ZekeSmith's latest version the most so far! There's a lot of good ideas in there. The orthogonal perspective of a grass block cropped to a pentagon well conveys it's related to Minecraft while being a visual pun on to the name, as it forms a regular _poly_gon. In fact, I like the visual pun so much I personally think the Ouroboros is detracting from it and clutters it.

Of course, I understand the symbolism, but I think that without that element the icon has a more "timeless" design.

I'm also not sure if it was intentional, but that specific yellow and black color scheme (on the tentative current logo) really reminds me of Anarcho-capitalism, which I don't think should be relevant or related to this project.

**Comment by ZekeZDev** [comment]
@binex-dsk suggested I use Ouroboros but I do agree with you that it may look better without, I am working on that currently since I am not a huge fan either. However I do think that it does bring familiarity that this is similar to multimc and may take some of that audience. 

Yeah the current yellow and black design does not really suit well I agree it probably fits that sort of "anarchy" design as well as other things that may not be desired when thinking of a minecraft launcher. I thought it was some sort of military shooter game or something at first when I saw it on flathub.

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148635316-fd0cc4d5-98c5-4472-8150-c82f7333a0e8.png)
![Polymchdlogoless](https://user-images.githubusercontent.com/81902668/148635328-796a60e2-db50-4f23-87ca-ef978ec22e2a.png)
Here's what it looks like without modifications removing the logo

**Comment by edward-shen** [comment]
Yeah, I definitely think it looks better without it. Certainly has a professional vibe to it!

**Comment by ZekeZDev** [comment]
Thanks, im open to feedback and I will be improving it before its at a production ready level.

**Comment by konradmb** [comment]
> really reminds me of Anarcho-capitalism, which I don't think should be relevant or related to this project.

When I've seen this color and a snake in that style, it reminded me of "Don't tread on me" flag, which really is in spirit of this project. "Don't tread on us MultiMC, because we will fork it". 😉

**Comment by edward-shen** [comment]
Of course; I understand the intention. Just wanted to bring up potential unintentional associations, because people will make assumptions, regardless of the intent.

For example: the Gadsden flag has had recent prominent exposure in US news as a political flag. People might interpret this as support for that political party, which they may or may not appreciate, and may or may not cause drama.

It may be in the project's best interest to also avoid any political connotation as well, if just to avoid any extra drama in the future. Given the reason to fork to begin with, I don't think anyone here wants to bother with _that_ potential headache in the future.

There's a lot of hypotheticals, I'm aware, but people have made complete forks over connotations (see the GIMP fork and glimpse, for example), so it's not unrealistic.

**Comment by d-513** [comment]
I too agree the latest logo looks better without ourboros, and definitely is more fitting for the name

**Comment by ZekeZDev** [comment]
Do you guys think it should be textured similar to how the default minecraft launcher is or does the simple work better I think it does.

**Comment by d-513** [comment]
IMO the current texture fits better with the Linux app art style generally

**Comment by ZekeSmith** [comment]
![Polymchd](https://user-images.githubusercontent.com/81902668/148638400-699a8579-9dd8-485c-9406-8e9c99f56154.png)
New design color and gradient balance

**Comment by ZekeZDev** [comment]
![Polymchd](https://user-images.githubusercontent.com/81902668/148638512-d7b34543-3e36-4dc5-9a12-20a7ebaabe47.png)
New design with grass looking like grass and gradient fixes

**Comment by ZekeZDev** [comment]
![Polymchd](https://user-images.githubusercontent.com/81902668/148638696-85ea76c8-7f4d-4f07-b709-2d48f798d415.png)
heres with ouroboros if we want to stick with ouroboros I will change the drop shadow a bit

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148638753-60496f7b-9bb0-4553-b2ef-ee2bff183f11.png)
![image](https://user-images.githubusercontent.com/81902668/148638766-30b4b4f0-af57-466b-babf-9bce901753c1.png)
Heres both in icon view

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148643928-39a9e9e0-4f1a-4c79-8226-fa832d2c1ac7.png)
I have been modifying the readme to see how the logo fits I also created a text version of the logo.

**Comment by d-513** [comment]
Looks good, IMO. Also the flathub button is a nice addition

**Comment by ZekeZDev** [comment]
yeah I was thinking of adding the microsoft store next to it if we decide to package it that way and other mainstream methods if we choose so.

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/81902668/148643928-39a9e9e0-4f1a-4c79-8226-fa832d2c1ac7.png)
> 
> I have been modifying the readme to see how the logo fits I also created a text version of the logo.

Looking through this I do understand the whole perspective of not wanting Ouro. This logo looks great and later I will implement it, unless here are objections.

**Comment by konradmb** [comment]
What do you think about a mix of two versions? Pixel art adds Minecrafty feeling and infinity sign keeps reference to MultiMC.
![bitmap](https://user-images.githubusercontent.com/925302/148654710-caa51523-16fb-4de7-b173-802aa0c3ec03.png)

**Comment by yemouu** [comment]
Feels like a class of styles by mixing them

**Comment by konradmb** [comment]
Do you mean very good (like in "classy") or very bad (like in "school of styles")? 😅

**Comment by yemouu** [comment]
I meant clash, typo lol

**Comment by konradmb** [comment]
Maybe if zig-zag grass edge would be pixelated, then it would fit better?

**Comment by konradmb** [comment]
Something like this, but more pro:
![Polymchd](https://user-images.githubusercontent.com/925302/148656530-3dd8a21b-9a6a-4bd2-8147-183cd0f81d6d.png)

Also, MultiMC logo has the same "clash of styles", so it would be more recognizable to former users, but not too similar.
![obraz](https://user-images.githubusercontent.com/925302/148656629-422eff12-ed89-4452-8f57-cb94a05ca3a6.png)

**Comment by ZekeZDev** [comment]
Pixel art is great but most of the time it does not work very well in a logo since the image needs to scale a lot and be used in different places it does not make sense to make it pixel art. I dont really like having ouroboros in the logo and having it at such a small scale wont work well especially when its clashing styles

**Comment by konradmb** [comment]
> the image needs to scale a lot and be used in different places

You don't have to use the same icon at all scales. That's why freedesktop icon structure has all of those 16x16, 32x32 etc. folders. Take a look at what GIMP does with its smaller icons. The Wilber eyes are getting bigger and it loses its pencil at the smallest size. I've seen that Firefox does (or did lately) that too.
![obraz](https://user-images.githubusercontent.com/925302/148660363-3444f9ad-4698-4a60-8947-411840cec2e1.png)

https://gitlab.gnome.org/GNOME/gimp/-/blob/master/desktop/256x256/gimp.png
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/desktop/32x32/gimp.png
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/desktop/16x16/gimp.png

**Comment by ZekeZDev** [comment]
that is an option however with most modern applications you would just use an svg that works at most scales. It is a lot of effort to make it at different scales and unless the main focus is raster it doesnt make sense.

I also tested the mixed logo idea to see how it worked I dont think its bad but I am not convinced.
![image](https://user-images.githubusercontent.com/81902668/148660698-02e0eb37-08d5-4666-8652-5e946c190d4b.png)

**Comment by konradmb** [comment]
Looks good to me, in case of 16x16 you can even fallback to a simple infinity sign, or make ouroboros all black (without grey shadow). And something is wrong with this montage, because size for all variants is the same.

> the main focus is raster

Well, the main focus should be raster, and that's what should be shipped for sure. You design your icons as vector, but convert them to raster for end-user. Take a look at the [Freedesktop Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) - "Support for SVGs is **optional**."

GIMP ships both .png and .svg, but most of the time the png version for appropriate version is shown to me (in Gnome). 


> It is a lot of effort to make it at different scales

It is an effort, but not a lot of it. You simply make ~3 versions - for example: one for very small size (16x16), one for 32x32, and one big size (256x256). You create new versions mainly by deleting visible features. 😁

Another idea is that two versions are shipped: one symbolic (small, black-and-white) and one normal (big, colorful). 

https://gitlab.gnome.org/GNOME/gnome-text-editor/-/tree/main/data/icons

![obraz](https://user-images.githubusercontent.com/925302/148661085-9af48ab6-9a6c-4d01-8e23-a998464bfd09.png)
![obraz](https://user-images.githubusercontent.com/925302/148661088-a87dfca4-a9db-4ede-b55a-da8feab712ff.png)


[KDE HIG](https://develop.kde.org/hig/style/icons/) says that:

> Many icons come in multiple sizes. Each version should be visually optimized and pixel-perfect for its particular size. Larger sizes offer more opportunity for detail and visual pizazz, while smaller version should be stripped of everything not absolutely necessary.

**Comment by ZekeZDev** [comment]
> Another idea is that two versions are shipped: one symbolic (small, black-and-white) and one normal (big, colorful).

This is what I am more used to

**Comment by ZekeZDev** [comment]
![Polymchdsnake](https://user-images.githubusercontent.com/81902668/148661677-2a6a7f6b-85ea-4805-ad94-4bcd77760714.png)
heres a concept I dont really like it and I think it needs a lot of work

**Comment by konradmb** [comment]
> I dont really like it

For me it's quite the opposite. With that pixelated grass I get instant Minecraft reference.

**Comment by ZekeZDev** [comment]
only issue is how am I going to get the grass in the middle since the way shapes work

**Comment by ZekeZDev** [comment]
also all the pixel detail looks like blur in icon view

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/148661806-d6858680-0d1e-431b-bd24-e317d4a68b09.png)

**Comment by konradmb** [comment]
> only issue is how am I going to get the grass in the middle since the way shapes work

Maybe cut out this diamond? I don't know if it would look bad without it. 🤔
![obraz](https://user-images.githubusercontent.com/925302/148661933-4dc8a126-354b-4008-b061-f00b14d31561.png)



> also all the pixel detail looks like blur in icon view

That's okay, you can't see small details at those sizes anyway. If you want you can tune it with a specific version as I mentioned earlier.

And something is wrong with this montage from Ikona, because size for all variants is the same. They should be at different sizes like here: 
![obraz](https://user-images.githubusercontent.com/925302/148661964-33cd7b62-5ea6-4669-baff-7abbd521e41d.png)

**Comment by konradmb** [comment]
Maybe wait a while for a feedback from someone other than me 😅

**Comment by ZekeZDev** [comment]
yeah my ikona is bugged but it still shows the 32px which is most common.

**Comment by ZekeZDev** [comment]
![Polymchdsnake](https://user-images.githubusercontent.com/81902668/148662046-83cb4868-bb7c-442e-807b-19deb89729b0.png)

heres latest I went back settling with the triangles since they just work better with the shape however I think this probably works the best and I guess in a way it sort of symbolises modding in minecraft having the hd grass but a low res "modded" snake

**Comment by ZekeZDev** [comment]
@konradmb Im doing a vote in the discussion channel on matrix to see if we keep the snake

**Comment by ghost** [comment]
Okay, so I've merged @ZekeSmith 's new logo, and I think everything looks all good. If there are no objections, this will be closed

**Comment by TerminallyDied** [comment]
im a part of the mc community so im going to voice my opinion, i am not a fan of the new logo.
imo its not unique enough, its just like every minecraft logo in existance the dirt block.
and its too simple.

i honestly prefer the gold block with the ororboro, its not perfect it could be better but atleast its unique.

**Comment by iSeth500** [comment]
![squeeze](https://user-images.githubusercontent.com/15620903/148841609-657ad006-55e1-45f7-aeff-d5580735441d.png)
I never stopped working on the stretched cube idea. What about the ouroboro squeezing a block?

**Comment by ZekeZDev** [comment]
> im a part of the mc community so im going to voice my opinion, i am not a fan of the new logo. imo its not unique enough, its just like every minecraft logo in existance the dirt block. and its too simple.
> 
> i honestly prefer the gold block with the ororboro, its not perfect it could be better but atleast its unique.

While you arent wrong and I respect what your saying simple and familar isnt a bad thing. The gold block logo with ouroboros is very good however as I stated before it doesnt make sense for a minecraft launcher. Familarity is more important then uniqueness in this instace.

The yellow and gold logo also had other issues such as resembling political flags and symbolism that may not be desired.

**Comment by ZekeZDev** [comment]
> ![squeeze](https://user-images.githubusercontent.com/15620903/148841609-657ad006-55e1-45f7-aeff-d5580735441d.png) I never stopped working on the stretched cube idea. What about the ouroboro squeezing a block?

I actually really like this but I dont think it would work as a main icon mabye some 3d rended on the webpage or something else. Non the less great job!

**Comment by iSeth500** [comment]
![squeeze](https://user-images.githubusercontent.com/15620903/148852296-583a551e-29cc-4727-b18d-abf6e92315aa.png)
icon or not, it's fun to make.

**Comment by ZekeZDev** [comment]
No thats respectable, I like it.

**Comment by iSeth500** [comment]
![squeeze](https://user-images.githubusercontent.com/15620903/148862149-c7c04f7f-9ef0-4fb5-b2df-88f1ae531ae1.png)
Looking better all the time!

**Comment by ghost** [comment]
That looks pretty good!

Wouldn't hurt to make the snake's mouth bigger. Doesn't have to be Ouro but if you want to base it off of him it's fine

**Comment by iSeth500** [comment]
Who is Ouro?

**Comment by ZekeZDev** [comment]
The name of the snake that the original logo was based off. Ouroboros

**Comment by iSeth500** [comment]
ohh! a wider mouth then?

**Comment by iSeth500** [comment]
![squeeze](https://user-images.githubusercontent.com/15620903/148879141-3fb11c22-3506-475b-92a9-5870f9c2273a.png)

**Comment by iSeth500** [comment]
![squeeze2](https://user-images.githubusercontent.com/15620903/149234800-83d300ae-1457-4ba3-a9a7-b9d9d1e7cc8e.png)
Last version I put here, probably.
Came to my senses with the whole realistic snake thing lol

**Comment by ZekeZDev** [comment]
Needs some tapering on the tail looks very good.

**Comment by iSeth500** [comment]
Should the tail end be visible, or completely in-mouth?

**Comment by ghost** [comment]
in the mouth

**Comment by iSeth500** [comment]
![snake](https://user-images.githubusercontent.com/15620903/149251754-8d88290d-59f7-4836-b837-f262b1fa4d0c.jpg)

**Comment by ZekeZDev** [comment]
@binex-dsk we should remove the pin on this issue. I would also highly reccomend we pin the two high issues: #7 #27

**Comment by ghost** [comment]
Okay, I will do this later. Can't right now because phone cope

**Comment by iSeth500** [comment]
https://user-images.githubusercontent.com/15620903/149415172-87b0ad4b-3828-481d-a2e9-e027b88acb93.mp4

**Comment by ZekeZDev** [comment]
@binex-dsk you have pinned the others but this issue does not seem to be unpinned?

**Comment by ghost** [comment]
> @binex-dsk you have pinned the others but this issue does not seem to be unpinned?

Because there was an objection and I need to make sure everyone agrees to this logo.

**Comment by ZekeZDev** [comment]
Ahh ok understood.

**Comment by TerminallyDied** [comment]
you can close the issue the icon has grown on me and i can agree on the stuff ZekeSmith said

**Comment by ghost** [comment]
ok
