### ISSUE TITLE
[develop] closing mc causes polymc to crash

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#1136]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

develop

### Version of Qt

qt 6.3.0

### Description of bug

closing mc causes polymc to crash

### Steps to reproduce

- open an instance
- quit the game
- see polymc crashing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
I have also experienced this, but cannot consistently reproduce this

**Comment by flowln** [comment]
It seems to be reliably reproducible when launching an instance with mods, and leaving the instance settings window open. The problem boils down to the resources being destroyed after launching the instance, and later being accessed as if they weren't. Since they are a shared_ptr in ResourceFolderModel, i think this has something to do with they living in another thread that gets garbage-collected by Qt later on, due to them being created in a task that gets thrown in a separate thread.

**Comment by flowln** [comment]
Yeah, checked and using `moveToThread(nullptr)` seems to fix this problem. However, that excludes the possibility of event processing on the resources, so it's not the most clean solution :/
For some reason, associating the resource to the main thread doesn't help either, it still gets destroyed.

**Comment by forkiesassds** [comment]
This issue is very annoying, every time I need to launch the game to work on something the launcher keeps segfaulting once I go to launch it or do other things with the instance.
