### ISSUE TITLE
Modrinth mrpack client- and server overrides

### ISSUE THREAD

**Issue by nothub** [PolyMC/PolyMC#1137]
### Operating System

Linux

### Version of PolyMC

1.4.1
1.4.2
5.0-develop

### Version of Qt

Qt 5.12.8

### Description of bug

When importing an mrpack archive, for overrides, only the `overrides` directory is processed.
The `client-overrides` and `server-overrides` directories are ignored and just extracted to the instances base directory.

### Steps to reproduce

`Add Instance` -> `Import from zip` an mrpack archive that contains one or both of `client-overrides` and `server-overrides`, e.g. [this one](https://modrinth.com/modpack/rinthereout/version/0.4.4-indev).

### Suspected cause

The cause is probably a missing implementation of handlers for the `client-overrides` and `server-overrides` directories, defined in the [mrpack spec](https://docs.modrinth.com/docs/modpacks/format_definition/#storage).

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
For `server-overrides`, I believe those are supposed to be used only in a dedicated server configuration, so that's why we don't take them into account, as we're only a client launcher as of now.

With that said, I can't seem to reproduce this issue very well :/
Trying the pack you linked in your description, I can see that, while the original client and server overrides folders do remain in the root instance path, as you've said, and that's certainly an issue, it seems to me that `client-overrides` are actually being correctly applied to the `.minecraft` folder, for instance, the `servers.dat` file from the `client-overrides` is in fact present in the root minecraft folder. Can you confirm to me whether this behavior is the same one you observe?

Also of note, it seems that empty directories in those overrides are also ignored, so that's another issue.

**Comment by nothub** [comment]
Oh, I can reproduce the behavior you are describing. I kinda messed up while testing. Since the 1.4.2 update the mrpack imports are successful. The bad behavior i tested is actually only occuring on MultiMC. This issue is invalid.
