### ISSUE TITLE
Aria2c as download client

### ISSUE THREAD

**Issue by DrMkdaddy** [PolyMC/PolyMC#1156]
### Role

I play modded minecraft.

### Suggestion

Use Aria2c as the download client for PolyMC in order to have multithreaded downloads/multiple downloads at a time.

### Benefit

Heavily speeds up downloading modpacks from curseforge. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
We already download more than one thing at a time

**Comment by flowln** [comment]
Yep, resource downloads are already concurrent, even if not multi-threaded. I'd say we don't really need to make downloads multi-threaded either, considering the pain of setting it up right outweighs the benefits of it, since most CPU time in the download is spent waiting for the net response.

Even if we were to switch approaches off the current task system, I'm more inclined on going the route of using ThreadWeaver's Collection to manage multiple download tasks at once. Perhaps even integrating with some Qt network resource monitor to adjust to different network speeds and stuff.
