### ISSUE TITLE
"Open Pack Folder" button does nothing.

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [PolyMC/PolyMC#1192]
### Operating System

Linux - Ubuntu 22.04 LTS

### Version of PolyMC

PolyMC 1.4.2

### Version of Qt

Qt 5.15.6

### Description of bug

The "OPEN PACK FOLDER" in game, while adding datapcks to yet-to-be created world, does nothing.

### Steps to reproduce

1- open 1.19.2 minecraft with PolyMC
2- click "SINGLEPLAYER"
3- click "DATA PACKS" button
4- Click "OPEN PACK FOLDER" button
5- Nothing happens! (file manager- nautilus in my case- should pop up)

### Suspected cause

Totally not a expert. But flatpak permissions maybe?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
SteamOS bug

**Comment by DioEgizio** [comment]
I think this is a bug with your OS

**Comment by Kushagra-Srivastava** [comment]
how can it be resolved?? Do you have any idea?

**Comment by Scrumplex** [comment]
It could also just be the case that the folder didn't exist yet?

**Comment by TayouVR** [comment]
it opens this on windows... I think this is a flatpak permissions issue..
![image](https://user-images.githubusercontent.com/31988415/195100937-2aba6239-4304-4190-a6f5-8217364e91a8.png)
might need to make it have access to `~/.temp/` or something.. not sure where mc does it on linux, but should be easy to test.

**Comment by ghost** [comment]
Does `xdg-open` open the folder? Make sure your XDG settings are correct.

**Comment by Nik-mmzd** [comment]
I have the same problem. ArchLinux, latest PolyMC release from AUR (built from source) (I also tried the flatpak version with the same result), no "open directory" buttons work. No problems with other programs, xdg-open works fine.
It looks like Prism has the same problem and tries to fix it (at least for non-flatpak users) by removing the legacy MultiMC indirectOpen workaround in `launcher/DesktopServices.cpp` completely (see PR 1954 from their repo).
It looks like this workaround is really obsolete: I can't find it in other popular programs, like [QBittorrent](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/utils.cpp#L124).

P.S. Flatpak support can be a pain: in my project I had to implement DBus support (`org.freedesktop.portal.Desktop`, `OpenDirectory` method) to open folders from a flatpak installation with correct mappings to host filesystem. The problem is `OpenURI` XDG-Portal method (seems to be used by QT) [does not support](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.OpenURI) `file://` schema, you required to use OpenFile/OpenDirectory methods

**Comment by ghost** [comment]
Interesting. I'm very busy but i'll take a gander at it within the next week or so.

**Comment by Nik-mmzd** [comment]
I have compiled PolyMC with the removed `indirectOpen` workaround and can confirm that it fixes the "Open Folder" buttons for non-flatpak installations.

I tried searching QT sources and found that it uses the [OpenURL](https://github.com/qt/qtbase/blob/dev/src/gui/platform/unix/qgenericunixservices.cpp#L472) and [OpenFile](https://github.com/qt/qtbase/blob/dev/src/gui/platform/unix/qgenericunixservices.cpp#L506) XDG Portal methods but doesn't care about `OpenDirectory`, but you can use [their implementation of the `OpenFile` call](https://github.com/qt/qtbase/blob/dev/src/gui/platform/unix/qgenericunixservices.cpp#L168) as a reference

**Comment by ghost** [comment]
> that it fixes the "Open Folder" buttons for non-flatpak installations.

I'd much rather find a fix that works for both flatpak and non-flatpak installations.

**Comment by Nik-mmzd** [comment]
The only way to support Flatpak is to implement [the `OpenDirectory` call](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-method-org-freedesktop-portal-OpenURI.OpenDirectory) by yourself (or find an external dependency?) with the `QDesktopServices::openUrl` call as a fallback for non-DBus non-Flatpak installations.

**Comment by Nik-mmzd** [comment]
Good news: I was wrong about Flatpak support. This patch works for Flatpak installations as well.
![image](https://github.com/PolyMC/PolyMC/assets/19509291/a24af331-40d3-41c6-8686-ca623557f05f)

~~I can spend some time, apply the full patch from the Prism repo and submit here as a PR~~
You can check the patch [in my fork](https://github.com/Nik-mmzd/PolyMC/tree/open-paths-directly)

**Comment by ghost** [comment]
Awesome. Open a PR here and I and others will review it.
