### ISSUE TITLE
Instance Issues, FTB One - No Mods Downloaded

### ISSUE THREAD

**Issue by vser** [PolyMC/PolyMC#1549]
Hey all, 
When setting up a FTB Modpack - It displays the version correctly, attempts to download mods but once Minecraft launches only two mods are enabled / installed. 

Modpack: FTB One v1.3.0
Enabled Items Upon Launch: Minecraft 1.19, Forge 41.0.63

Using the standard Overwolf/FTB App installs all mods correctly.

**Comment by jdpatdiscord** [comment]
Do name where you got this PolyMC instance from. Built from source, downloaded from the site, if so - which and so on. Which OS. There is a regular issue layout form for this!

**Comment by vser** [comment]
> Do name where you got this PolyMC instance from. Built from source, downloaded from the site, if so - which and so on. Which OS. There is a regular issue layout form for this!

Apologies- see below;
**OS:** Windows 11 22H2
Standard compiled version from Poly website (Poly 5.0)
**Build date:** 2023-02-04
**Commit:** 7b547c842c880bbc42ecf351d47e439b36cd1b21
**Channel:** 7b547c84

**Comment by GG3Hahn** [comment]
I was having the same problem on the 5.0 release: none of the FTB (non-legacy) modpacks would actually contain any loader mods after installing -- even though PolyMC's network activity and logs pointed towards downloads being successful. Installing modpacks from CurseForge would work fine.
This seems to be fixed in the latest commit though.

**Comment by LennyMcLennington** [comment]
This was fixed in 5.1
