### ISSUE TITLE
People won't install unsigned executables

### ISSUE THREAD

**Issue by Falconerd** [PolyMC/PolyMC#1568]
### Version of PolyMC

Latest

### Version of Qt

Unsure, can't install

### Description of bug

I tried to get my friends to use PolyMC but they will not because it's flagged by Windows Defender.

### Steps to reproduce

Try to install the program.

### Suspected cause

Unsigned executable.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
This is not a bug, certificates for executable signing cost a lot of money and they need to be renewed every year. If they don't trust it because of the Windows Smartscreen warning, that is their personal issue and not a problem with the software.

The source code and Github Actions workflow that builds and packages the software is publicly auditable, if code signing is what they think differentiates malware from legitimate software then that is not something I can help them with.

**Comment by Falconerd** [comment]
That sounds like extortion - not surprised... I just looked it up and it ranges from $80 - $800 per year. I can see why people don't want to pay that.

These people are normies, so they cannot read the code and verify it themselves. Fair enough.

**Comment by KaspianDev** [comment]
send them a link to the repo to audit it?

Edit: signing also doesnt make your program virus free lol it just proves u signed it
