### ISSUE TITLE
AUR Packages Will Not Build

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1572]
### Operating System

Linux

### Version of PolyMC

5.1-1

### Version of Qt

Qt 5

### Description of bug

Will not build. Tried all packages from the AUR.

Just get this error somewhere along the line of building.
This was with polymc-qt5-git:

[  8%] Linking CXX static library libhoedown.a
[  8%] Built target hoedown
[  8%] Building Java objects for NewLaunch.jar
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:93: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [CMakeFiles/Makefile2:591: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'polymc-qt5-git-5.0.r0.g7b547c84-1': 
error: packages failed to build: polymc-qt5-git-5.0.r0.g7b547c84-1
Press any key to continue...

This was with polymc-git:
[  5%] Building CXX object libraries/hoedown/CMakeFiles/hoedown.dir/hoedown_autogen/mocs_compilation.cpp.o
[  5%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/autolink.c.o
[  5%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/buffer.c.o
[  5%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/document.c.o
[  6%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/escape.c.o
[  6%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/html.c.o
[  6%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/html_blocks.c.o
[  6%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/html_smartypants.c.o
[  6%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/stack.c.o
[  7%] Building C object libraries/hoedown/CMakeFiles/hoedown.dir/src/version.c.o
[  7%] Linking CXX static library libhoedown.a
[  7%] Built target hoedown
[  7%] Building Java objects for NewLaunch.jar
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:93: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [CMakeFiles/Makefile2:1382: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'polymc-git-5.0.r0.g7b547c84-1': 
error: packages failed to build: polymc-git-5.0.r0.g7b547c84-1

### Steps to reproduce

Install from AUR, will not work.

### Suspected cause

Not too sure what the cause could be. I am on a fresh install of Garuda Linux and installing from the AUR.
I am running normal OpenJDK 20, but also tried with 17 and 18, as well as Temurin.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by boinkitsbroken** [comment]
I AM NOT AN EXPERT, but...

From what I can tell, this looks like a "file not found" error. That's weird, because the files in question are being made during the build process. Or at least they should be. If they're not being made, it's most likely because cmake doesn't have permission to write them. Hence, this could be a permissions error. Try checking file/folder permissions under polymc/libraries/launcher, test file write permissions by trying to make a new file or folder manually, or just set the folder permissions to 7777 (read/write for all).

You can also check your version of cmake to see if it's some sort of weird custom version, just in case.

Or you can grab a VM image of Arch Linux and retry the build in there.  If it works, you know you have an OS-specific compatibility issue, i.e. Arch is supported but Garuda isn't.

**Comment by HeyaGlitz** [comment]
You need to default to an earlier Java version, as shown in the screenshot, Java 20 doesn't support compiling for 1.7, while 17 does. Preferably use Java 8 though. Most likely the issue is that you didn't change the compiler version for cmake. I highly recommend you use Java 17 as your default since it's LTS.
![image](https://user-images.githubusercontent.com/30732772/235101664-436a62d4-0432-4ba2-89b2-c5adbe110d14.png)
