### ISSUE TITLE
mod and modpack selector randomly select wrong things

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#204]
### Operating System

Windows, macOS, Linux

### Description of bug

mod and modpack selector randomly select wrong things

### Steps to reproduce

- try to install a mod or a modpack and select fastly the mods
- see

### Suspected cause

no idea
<img width="1178" alt="Schermata 2022-02-27 alle 09 44 16" src="https://user-images.githubusercontent.com/83089242/155875288-629dc3f3-3734-45eb-9ead-d4d6c5a8545a.png">
<img width="1451" alt="Schermata 2022-02-27 alle 09 43 44" src="https://user-images.githubusercontent.com/83089242/155875291-ba53aa63-fb1e-42eb-8621-c3c0ec6ab556.png">

NOTE: this happens on multimc modpack selector too
### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by timoreo22** [comment]
Can confirm, this seems to happen if the version data finishes loading but the user has already changed.
This could be fixed by checking if the mod's id corresponds to the version's id when requested, and if it does not match, discard the data. this fix should also be ported over to the modpack selection area, since it uses the same logic
