### ISSUE TITLE
Drag and Drop in Edit Instance not working in Flatpak

### ISSUE THREAD

**Issue by TheKodeToad** [PolyMC/PolyMC#317]

**Comment by luni3359** [comment]
I feel this is an issue that happens to all flatpaks due to the nature of sandboxing. To get around this issue you can give PolyMC `filesystem=home` permissions through Flatseal (a Flatpak permission manager) or by running the following command: 
`flatpak override --user --filesystem=home org.polymc.PolyMC`

It defeats part of sandboxing but it's functional.

**Comment by ghost** [comment]
You could also add specific directories from which to import as read only. For example I added `xdg-download:ro` in flatseal. This could be a sane default to avoid confusion as most people will try to import datapacks etc. from there.

**Comment by Scrumplex** [comment]
@Der-Hampelmann's suggestion sounds good to me. A prominent example which allows `xdg-download` is Discord's Flatpak

**Comment by d-513** [comment]
I added the xdg-download:ro permission to the beta branch

**Comment by luni3359** [comment]
Does this include the desktop folder too? I like to use it as a temporary place to put files sometimes

**Comment by ghost** [comment]
@luni3359 No that would be `xdg-desktop:ro` then. I'd not include that as a default but maybe I am just to used to the "gnome-way".

**Comment by d-513** [comment]
It doesn't. You have to add that yourself.

Downloads as read only seems to be most reasonable. I'll see if I can get portals working

**Comment by TheKodeToad** [comment]
Does it allow subdirectories?

Just so you can add mods straight from unzipping GitHub actions.

**Comment by d-513** [comment]
Yes, xdg-download by extension means any directory in it too.
