### ISSUE TITLE
Support websites that don't use `https://0x0.st`'s format

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#441]
### Role

I want to be able to access easily for more crashlog upload webistess

### Suggestion

Support websites that don't use `https://0x0.st`'s format

### Benefit

Support more crashlog upload websites (eg. https://crashy.net)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LennyMcLennington** [comment]
It should be a lot easier to add new formats in the future now I laid the foundations in #554 but I don't think we will add support for crashy.net because it seems to be proprietary and it doesn't have any API documentation so I don't think it's possible to add support for it until they add a stable API that we can rely on to make use of it.

**Comment by LennyMcLennington** [comment]
I think this can be closed when #554 is merged but a new issue could be made if someone wants to request support for a specific service that wasn't implemented in that PR.
