### ISSUE TITLE
Show English in translations first

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#48]
The first language in the language chooser is chineese, and you have to look in the list to find English. I think it should be on the top as the majority of pepole will use English anyway.

**Comment by oynqr** [comment]
It already defaults to en_US, you just have to click next. Considering the system locale instead of just using English by default would probably be the best option IMHO.

I agree that not seeing American English selected in the GUI even though it is, in fact, selected by default, is kind of weird UX.

**Comment by d-513** [comment]
Oh. Yeah though selecting it and showing its selected + using the locale language from system would be better UX.
