### ISSUE TITLE
[Suggestion] Download mods menu should only check for *enabled* MLs

### ISSUE THREAD

**Issue by RuinTD** [PolyMC/PolyMC#508]
When using the download mods menu, it should only check for *enabled* mod loaders. Currently, if you have both Fabric and Quilt installed but only Quilt enabled, the menu doesn't even list Quilt Standard Libraries as an available mod because it's only listing Fabric mods.

**Comment by txtsd** [comment]
Please use the Suggestion template next time.

**Comment by kthchew** [comment]
> Currently, if you have both Fabric and Quilt installed but only Quilt enabled, the menu doesn't even list Quilt Standard Libraries as an available mod because it's only listing Fabric mods.

I'm pretty sure that even if you only have Quilt enabled, it'll show you Fabric mods. I think this was done because most mods that are marked as working with Fabric work with Quilt right now, and few mods are marked as working with Quilt (so it's more useful to show mods that work with Fabric instead). This seems temporary, though; I assume that once more mods are marked as Quilt-compatible, the launcher will then show Quilt-compatible mods for Quilt as normal.

**Comment by RuinTD** [comment]
> I'm pretty sure that even if you only have Quilt enabled, it'll show you Fabric mods.

I've already tested this. Having just Quilt installed shows both Fabric and Quilt mods, including QSL. However, if Fabric is also installed (even if disabled), QSL and other Quilt only mods disappear.

**Comment by Nolij** [comment]
> > I'm pretty sure that even if you only have Quilt enabled, it'll show you Fabric mods.
> 
> I've already tested this. Having just Quilt installed shows both Fabric and Quilt mods, including QSL. However, if Fabric is also installed (even if disabled), QSL and other Quilt only mods disappear.

This should really be changed, I spent the past hour trying to find out why QSL doesn't show on PolyMC. Probably not an uncommon scenario given many users are being forced to migrate to Quilt due to a bunch of mods suddenly going Quilt only, and it's easier to revert if some mod won't work on Quilt to just disable Fabric and install Quilt instead of having to reinstall Fabric if it doesn't work.
