### ISSUE TITLE
Change the `_LAUNCHER_TEMP`'s folder to the PolyMC folder and not the instance folder

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#524]
### Role

I change the location of my MC instances

### Suggestion

To move the `_LAUNCHER_TEMP` folder to the PolyMC main folder (for Linux `~/.local/share/PolyMC`)

### Benefit

A useless for the user folder won't appear in the instance folder

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It could also be completely removed, but I'm unsure of its purpose so maybe not

**Comment by kthchew** [comment]
If it's actually temporary, it probably makes sense to use the temporary directory provided by the OS (e.g. `$TMPDIR` on Mac/Linux) so it's out of the way and automatically gets cleaned up. Qt even provides [a function](https://doc.qt.io/qt-5/qdir.html#tempPath) to do so on all platforms.

**Comment by Scrumplex** [comment]
That directory is used while creating instances. So if PolyMC were to crash during instance creation, you wouldn't have a broken instance. Having it in the instances directory makes sense, as that will make sure, once the instance is ready, moving the instance to the actual location will be instantaneous, rather than having the possibility of needing a copy (for example accross mountpoints / drives)

**Comment by Scrumplex** [comment]
Maybe we should rename it to `.launcher-temp` and hide it on platforms like Windows.
