### ISSUE TITLE
Provide Windows installer

### ISSUE THREAD

**Issue by clydebottoms** [PolyMC/PolyMC#66]
One way that PolyMC can improve over multimc is windows packaging. How would this be done?

**Comment by GriffintheFolf** [comment]
I know that MultiMC doesn't have a proper installer app (e.g. one made with [NSIS](https://nsis.sourceforge.io)), but that's about all I can think of for potential Windows packaging improvements myself.

There is a Windows build in the README, although I'm not sure how official it is. In my own testing, I found all of the icons are missing as well, likely due to paths that forgot to be changed. It's also only 32-bit as well; not so important since it's just the launcher, but a 64-bit build would be great too.

**Comment by ZekeSmith** [comment]
Im not a windows user but I do have to agree this is an important issue. Also is there any reason for the launcher currently 32bit on windows?

**Comment by binex-dsk** [comment]
win64 build was broken

**Comment by ZekeSmith** [comment]
Ahh ok how much effort would it take to fix and does it work upstream?

**Comment by binex-dsk** [comment]
From what I remember upstream does not provide details for a build on MinGW.

Ask @LennyMcLennington as he was the one behind the whole process.

**Comment by Schmensch** [comment]
Maybe port to WinGET?

**Comment by HalJordan** [comment]
> Im not a windows user but I do have to agree this is an important issue. Also is there any reason for the launcher currently 32bit on windows?

Would there be any impactfull benefit to it being 64-bit tho?

It's just the launcher. It's not doing /that/ much. It's certainly not going to be going over any 32-bit memory limits.

**Comment by dada513** [comment]
what about porting https://github.com/MultiMC/Launcher/pull/3360? Seems to be a good way to do this. The CI will be on GHA so windows build isnt a problem

**Comment by TheKodeToad** [comment]
I think Squirrel would be a better choice than NSIS. It's just personal preference, though.

**Comment by OldWorldOrdr** [comment]
we should use opencandy and bundle some shitty antivirus.
