### ISSUE TITLE
Duplicate 'kill' button in MacOS menu bar

### ISSUE THREAD

**Issue by Arthurmeade12** [PolyMC/PolyMC#695]
### Operating System

MacOS

### Version of PolyMC

PolyMC 1.3.0-dca4ea5c

### Description of bug

In the PolyMC menu bar on MacOS, the kill button is listed twice.
<img width="469" alt="Screen Shot 2022-06-01 at 6 53 08 PM" src="https://user-images.githubusercontent.com/71673838/171520605-7c54b981-0b5d-4ff9-961b-78d0136e0aa1.png">

### Steps to reproduce

Open PolyMC, then click 'File' in the menu bar to see the duplicate.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I can reproduce

**Comment by forkiesassds** [comment]
Seems to be a macOS specific bug, as I can't repro on Linux.
![image](https://user-images.githubusercontent.com/54495659/171681599-11382ad8-cb7f-493c-8c85-168f03e884f7.png)

**Comment by kthchew** [comment]
Apparently this happens every time a running instance is selected. If you keep selecting and deselecting a running instance, more kill commands will appear.

From random experimentation it seems like commenting out these two lines "fixes" this issue:

https://github.com/PolyMC/PolyMC/blob/147bde5294626d7ba1a6cd672200f7da878eddd9/launcher/ui/MainWindow.cpp#L1166-L1167

But obviously that isn't the full solution, as it breaks the kill button (it remains a dropdown instead of being a button). I guess macOS gets confused when the dropdown turns into a button, and then duplicates the action each time this happens.



> Seems to be a macOS specific bug, as I can't repro on Linux. ![image](https://user-images.githubusercontent.com/54495659/171681599-11382ad8-cb7f-493c-8c85-168f03e884f7.png)

This behavior is still kind of weird though. It doesn't really make much sense for a launch command to be behind a dropdown labeled "kill." But I'm not sure why the behavior is different on Linux - it seems like the code is supposed to make that button a dropdown with those options when it is labeled "Launch," and a regular button when it is labeled "Kill."
