### ISSUE TITLE
Include Java 18 on the PolyMC Flatpak 

### ISSUE THREAD

**Issue by mateowoetam** [PolyMC/PolyMC#823]
### Role

I play moded Minecraft

### Suggestion

I want the java installations to include Java 18

### Benefit

Java 19 is almost out so you might as well.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
It'd be completely useless, Minecraft just needs java 8 and java 17

**Comment by cmspeedau** [comment]
minecraft 1.18 requires java 18 including for forge and mods now. they changed the sdk requirments. not sure when but i can confirm 1.18 dosent work on anything lower. and java 8 is good for any verison up till then. java 17 will help with some modpacks..

**Comment by DioEgizio** [comment]
> minecraft 1.18 requires java 18 including for forge and mods now. they changed the sdk requirments. not sure when but i can confirm 1.18 dosent work on anything lower. and java 8 is good for any verison up till then. java 17 will help with some modpacks..

That's just false, Minecraft 1.18 requires java 17

**Comment by Scrumplex** [comment]
Java 17 is a LTS release, which is why future Minecraft versions will probably all use that as a baseline. Java 18 will be unsupported in a few months. Minecraft 1.18 and later require Java 17. Minecraft 1.17 officially requires Java 16, but 17 works fine as well. And everything before that requires Java 8.
