### ISSUE TITLE
The ability to install 2+ modpacks in the same instance

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#898]
### Role

I wanna make a modpack and use it alongside with another modpack I already use

### Suggestion

To give the ability to install 2+ mospacks in the same instance

### Benefit

People will run their favorite modpacks together

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

#894 is an extra reason, since you can still install 2 modpacks by coping and pasting the one instance to the other..

**Comment by ivanpu** [comment]
Modpack isn't just a "collection of mods", but usually comes with at least a whole bunch of tweaks to the configurations of these mods. Two separate modpacks, while having the same exactly mods, can have very different user experience because of the different configurations. Do you have any resolution in mind to the configurations conflicts between the modpacks? "coping and pasting" the whole instance will simply overwrite the configuration with the later modpack, while copying only the mods folder will neglect all the configurations from it. And to the devs of which of the modpacks are you going to report the bugs caused by merging two (or more) packs into single instance?

**Comment by RaptaG** [comment]
> Modpack isn't just a "collection of mods", but usually comes with at least a whole bunch of tweaks to the configurations of these mods. [...]

I'm aware of that, you are right about the bug reporting but after all, there could be a disclaimer for that. Remember, it's just an option, not something you are forced to do. If somebody decides to install 2 modpacks together, they'd be aware of these issues..

**Comment by ghost** [comment]
It's not that it may mess up, it will. as @ivanpu said, modpacks make tweaks to individual mods and the way they interact with each other. Installing two separate modpacks in the same instance would overwrite those individual changes and conflict. I don't see any scenario where it works without jeopardizing one thing.

_If_ you really like a mod from a mod pack, it's probably safer to do it manually in this case.

**Comment by RaptaG** [comment]
Ok, I assume my idea is irrelevant, I'm closing this issue
