### ISSUE TITLE
add possibility to have more than 6 concurrent downloads, and add a settings for it

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#915]
### Role

i use polymc

### Suggestion

being able to have concurrent tasks and so downloads is already a big win, but it's currently limited to 6 tasks, which is good but more would be cool. additionally, a setting for choosing how many concurrent tasks like gdlauncher would be very cool and convenient 

### Benefit

better performance = better

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
This becomes problematic once you start thinking about the traffic on the server side. More concurrent downloads may make things quicker for the end user, but will also strain more the serving server, potentially reaching the rate limit and/or getting the user's IP banned. From what I could gather, both Qt and Firefox use 6 concurrent tasks, because it seems to be a good compromise, so that's what I went for.

Implementing this setting is quite straightforward in the code, but for the reason stated above, IMO this either needs to be done with extra extra care, or not at all :|
