### ISSUE TITLE
switch to a tab-based approach to minecraft settings like the APIs page

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#935]
### Role

i use polymc

### Suggestion

i'd like a tab based approach to minecraft settings. rn on my linux machine the polymc settings window goes under my floating panel, which isn't very convienient

### Benefit

it'd make settings easier to access

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/83089242/179677838-89109ee7-8160-4ac0-8eb6-12917a127b6c.png)

**Comment by PantsAreForLegsNOTARMS** [comment]
So I see how the bottom of your window is partially eclipsed. Is that the problem? 
If so, how is a "tab based approach to Minecraft settings"  a fix for this issue?

Guess I am just trying to clarify what you are asking for because I've read it twice, and I'm still unclear as to what you need / are asking to be done.

**Comment by DioEgizio** [comment]
with tabs things would be easier because each tab could have some settings in it, making this not happen
