### ISSUE TITLE
mods list on launch is broken on macos in develop

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#942]
### Operating System

macOS

### Version of PolyMC

PolyMC 1.4.0 (develop)

### Description of bug

<img width="625" alt="image" src="https://user-images.githubusercontent.com/83089242/180263835-770ed38b-bae0-4e8b-b9fe-58fa0b241ec6.png">

### Steps to reproduce

- open an instance
- see the mods list

### Suspected cause

maybe qt 6?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
well it didn't happen before #575 was merged

**Comment by kthchew** [comment]
This only seems to happen for enabled mods, so the culprit seems to be the ✔️ symbol. Disabled mods (❌) and folders (📁) appear fine.

**Comment by Scrumplex** [comment]
Can't reproduce on my end. macOS specific?

**Comment by kthchew** [comment]
> Can't reproduce on my end. macOS specific?

Probably

I'd note that in Qt 5, the checkmark does not appear as a colored emoji while the other icons do:

<img width="43" alt="Screen Shot 2022-07-21 at 3 05 21 PM" src="https://user-images.githubusercontent.com/79120643/180296009-8335bedd-020e-4e84-978d-6b5fc4d32420.png">

I'm guessing this issue is related to this, but I'm not really knowledgeable about Unicode so I can't explain why.
